version: '3.7'

services:
    blazegraph:
        image: metaphacts/blazegraph-basic:2.2.0-20160908.003514-6-jetty9.4.18-jre8-alpine-0b8d0de
        hostname: blazegraph
        container_name: blazegraph
        ports:
            - "8889:8080"
            - "8890:80"

networks:
    default:
        name: migrator-test-network
